SQOOP-3159: Sqoop (export + --table) with Oracle table_name having '$' fails with error (ORA-00942 or java.lang.NoClassDefFoundError)
(Szabolcs Vasas via Anna Szonyi)

(cherry picked from commit afd6a86)